<a href="https://colab.research.google.com/github/bhumibansal-ux/Bhumi1/blob/main/working_with_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.importing pandas

In [1]:
import pandas as pd

2.opening a local csv file

In [3]:
df=pd.read_csv('StudentPlacementData.csv')
df

,Gender,Branch,College_Tier,CGPA,Internships,Projects,Aptitude_Score,Communication_Score,Technical_Score,Backlogs,Attendance_Percentage,Certifications,Coding_Rating,Placement,Salary_LPA
0,Female,IT,Tier 3,5.72,0,3,99,72,90,4,92.65,1,1806,0,0.00
1,Female,ECE,Tier 3,8.10,5,3,86,69,81,3,89.56,2,1163,0,0.00
2,Male,ECE,Tier 1,6.08,5,5,99,85,92,1,71.25,2,1946,1,16.17
3,Male,CSE,Tier 1,7.22,2,2,61,64,41,3,73.49,6,1697,0,0.00
4,Male,IT,Tier 1,9.03,2,4,99,89,43,4,98.56,6,920,1,15.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Male,CIVIL,Tier 1,9.70,1,3,76,70,70,2,78.76,5,1367,1,17.49
4996,Male,EEE,Tier 1,7.33,0,4,79,84,57,3,63.34,0,1064,1,13.20
4997,Female,EEE,Tier 1,6.61,5,7,63,58,80,3,60.31,0,1460,1,15.57
4998,Male,MECH,Tier 2,6.00,4,1,83,96,50,4,77.70,3,1070,0,0.00
4999,Female,MECH,Tier 2,6.58,3,8,75,97,52,1,83.65,0,1974,1,13.58

3.opening a local csv file through url

In [4]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

4.Sep parameter

In [40]:
pd.read_csv('movie_titles_metadata.tsv',sep='\t',names=['sno','name','release_year','rating','votes','genres'])

,sno,name,release_year,rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

5.Index col parameter

In [18]:
pd.read_csv('StudentPlacementData.csv',index_col='Branch')

,Gender,College_Tier,CGPA,Internships,Projects,Aptitude_Score,Communication_Score,Technical_Score,Backlogs,Attendance_Percentage,Certifications,Coding_Rating,Placement,Salary_LPA
Branch,,,,,,,,,,,,,,
IT,Female,Tier 3,5.72,0,3,99,72,90,4,92.65,1,1806,0,0.00
ECE,Female,Tier 3,8.10,5,3,86,69,81,3,89.56,2,1163,0,0.00
ECE,Male,Tier 1,6.08,5,5,99,85,92,1,71.25,2,1946,1,16.17
CSE,Male,Tier 1,7.22,2,2,61,64,41,3,73.49,6,1697,0,0.00
IT,Male,Tier 1,9.03,2,4,99,89,43,4,98.56,6,920,1,15.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CIVIL,Male,Tier 1,9.70,1,3,76,70,70,2,78.76,5,1367,1,17.49
EEE,Male,Tier 1,7.33,0,4,79,84,57,3,63.34,0,1064,1,13.20
EEE,Female,Tier 1,6.61,5,7,63,58,80,3,60.31,0,1460,1,15.57
MECH,Male,Tier 2,6.00,4,1,83,96,50,4,77.70,3,1070,0,0.00
MECH,Female,Tier 2,6.58,3,8,75,97,52,1,83.65,0,1974,1,13.58

6.header parameter

In [6]:
pd.read_csv('StudentPlacementData.csv',header=1)

,Female,IT,Tier 3,5.72,0,3,99,72,90,4,92.65,1,1806,0.1,0.2
0,Female,ECE,Tier 3,8.10,5,3,86,69,81,3,89.56,2,1163,0,0.00
1,Male,ECE,Tier 1,6.08,5,5,99,85,92,1,71.25,2,1946,1,16.17
2,Male,CSE,Tier 1,7.22,2,2,61,64,41,3,73.49,6,1697,0,0.00
3,Male,IT,Tier 1,9.03,2,4,99,89,43,4,98.56,6,920,1,15.51
4,Male,IT,Tier 1,6.62,2,4,87,78,99,3,98.97,1,1892,1,15.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4994,Male,CIVIL,Tier 1,9.70,1,3,76,70,70,2,78.76,5,1367,1,17.49
4995,Male,EEE,Tier 1,7.33,0,4,79,84,57,3,63.34,0,1064,1,13.20
4996,Female,EEE,Tier 1,6.61,5,7,63,58,80,3,60.31,0,1460,1,15.57
4997,Male,MECH,Tier 2,6.00,4,1,83,96,50,4,77.70,3,1070,0,0.00
4998,Female,MECH,Tier 2,6.58,3,8,75,97,52,1,83.65,0,1974,1,13.58

7.use_cols parameter

In [19]:
pd.read_csv('StudentPlacementData.csv',usecols=['Gender','Branch','College_Tier','CGPA'])

      Gender Branch College_Tier  CGPA
0     Female     IT       Tier 3  5.72
1     Female    ECE       Tier 3  8.10
2       Male    ECE       Tier 1  6.08
3       Male    CSE       Tier 1  7.22
4       Male     IT       Tier 1  9.03
...      ...    ...          ...   ...
4995    Male  CIVIL       Tier 1  9.70
4996    Male    EEE       Tier 1  7.33
4997  Female    EEE       Tier 1  6.61
4998    Male   MECH       Tier 2  6.00
4999  Female   MECH       Tier 2  6.58

[5000 rows x 4 columns]

8.squeeze parameter

In [25]:
pd.read_csv('StudentPlacementData.csv',usecols=['Gender']).squeeze()

0       Female
1       Female
2         Male
3         Male
4         Male
         ...
4995      Male
4996      Male
4997    Female
4998      Male
4999    Female
Name: Gender, Length: 5000, dtype: object

9.skiprows/nrows parameter

In [26]:
pd.read_csv('StudentPlacementData.csv',nrows=100)

,Gender,Branch,College_Tier,CGPA,Internships,Projects,Aptitude_Score,Communication_Score,Technical_Score,Backlogs,Attendance_Percentage,Certifications,Coding_Rating,Placement,Salary_LPA
0,Female,IT,Tier 3,5.72,0,3,99,72,90,4,92.65,1,1806,0,0.00
1,Female,ECE,Tier 3,8.10,5,3,86,69,81,3,89.56,2,1163,0,0.00
2,Male,ECE,Tier 1,6.08,5,5,99,85,92,1,71.25,2,1946,1,16.17
3,Male,CSE,Tier 1,7.22,2,2,61,64,41,3,73.49,6,1697,0,0.00
4,Male,IT,Tier 1,9.03,2,4,99,89,43,4,98.56,6,920,1,15.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Female,CIVIL,Tier 3,9.52,0,2,95,85,55,4,75.59,4,1708,0,0.00
96,Female,CSE,Tier 3,7.66,2,2,53,87,97,4,93.34,2,1991,0,0.00
97,Male,EEE,Tier 1,5.47,1,2,73,74,94,0,70.15,5,1057,1,12.25
98,Male,CSE,Tier 2,6.15,0,7,87,56,57,4,87.23,7,1789,0,0.00
99,Male,EEE,Tier 2,8.12,0,3,91,62,87,3,61.89,6,1880,0,0.00

10.encoding parameter

In [27]:
pd.read_csv('StudentPlacementData.csv',encoding='latin-1')

,Gender,Branch,College_Tier,CGPA,Internships,Projects,Aptitude_Score,Communication_Score,Technical_Score,Backlogs,Attendance_Percentage,Certifications,Coding_Rating,Placement,Salary_LPA
0,Female,IT,Tier 3,5.72,0,3,99,72,90,4,92.65,1,1806,0,0.00
1,Female,ECE,Tier 3,8.10,5,3,86,69,81,3,89.56,2,1163,0,0.00
2,Male,ECE,Tier 1,6.08,5,5,99,85,92,1,71.25,2,1946,1,16.17
3,Male,CSE,Tier 1,7.22,2,2,61,64,41,3,73.49,6,1697,0,0.00
4,Male,IT,Tier 1,9.03,2,4,99,89,43,4,98.56,6,920,1,15.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Male,CIVIL,Tier 1,9.70,1,3,76,70,70,2,78.76,5,1367,1,17.49
4996,Male,EEE,Tier 1,7.33,0,4,79,84,57,3,63.34,0,1064,1,13.20
4997,Female,EEE,Tier 1,6.61,5,7,63,58,80,3,60.31,0,1460,1,15.57
4998,Male,MECH,Tier 2,6.00,4,1,83,96,50,4,77.70,3,1070,0,0.00
4999,Female,MECH,Tier 2,6.58,3,8,75,97,52,1,83.65,0,1974,1,13.58

11.skip bad lines

In [54]:
pd.read_csv('BX-Books.csv', sep=';', encoding="latin-1", on_bad_lines='skip')

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
61048,0862412285,"The Changeling (Canongate Classics, Vol 22)",Robin Jenkins,1989,Canongate Books,http://images.amazon.com/images/P/0862412285.0...,http://images.amazon.com/images/P/0862412285.0...,http://images.amazon.com/images/P/0862412285.0...
61049,0140028374,The Highland clearances,John Prebble,1969,Penguin,http://images.amazon.com/images/P/0140028374.0...,http://images.amazon.com/images/P/0140028374.0...,http://images.amazon.com/images/P/0140028374.0...
61050,0413163806,Murder in the English Department,V. Miner,1988,Mandarin,http://images.amazon.com/images/P/0413163806.0...,http://images.amazon.com/images/P/0413163806.0...,http://images.amazon.com/images/P/0413163806.0...
61051,0786884320,Necessary Journeys : Letting Ourselves Learn F...,Nancy L. Snyderman,2001,Hyperion,http://images.amazon.com/images/P/0786884320.0...,http://images.amazon.com/images/P/0786884320.0...,http://images.amazon.com/images/P/0786884320.0...
61052,0930753054,Stupid Stories,Bob Leonard,1988,Spectacle Lane Press,http://images.amazon.com/images/P/0930753054.0...,http://images.amazon.com/images/P/0930753054.0...,http://images.amazon.com/images/P/0930753054.0...

12.dtypes parameter

In [33]:
pd.read_csv('StudentPlacementData.csv',dtype={'target':int}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Gender                 5000 non-null   object
 1   Branch                 5000 non-null   object
 2   College_Tier           5000 non-null   object
 3   CGPA                   5000 non-null   float64
 4   Internships            5000 non-null   int64
 5   Projects               5000 non-null   int64
 6   Aptitude_Score         5000 non-null   int64
 7   Communication_Score    5000 non-null   int64
 8   Technical_Score        5000 non-null   int64
 9   Backlogs               5000 non-null   int64
 10  Attendance_Percentage  5000 non-null   float64
 11  Certifications         5000 non-null   int64
 12  Coding_Rating          5000 non-null   int64
 13  Placement              5000 non-null   int64
 14  Salary_LPA             5000 non-null   float64
dtypes: float64(3), int64(9), object(3)
memory usage: 586.1+ KB

13.handling dates

In [36]:
pd.read_csv('IPL Matches 2008-2020.csv',parse_dates=['date']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    datetime64[ns]
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(13)
memory usage: 108.5+ KB

In [37]:
def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    else:
        return name

In [38]:
rename("Royal Challengers Bangalore")

'RCB'

14.convertors

In [39]:
pd.read_csv('IPL Matches 2008-2020.csv',converters={'team1':rename})

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,RCB,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,RCB,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

15.na_values parameter

In [15]:
pd.read_csv('StudentPlacementData.csv',na_values=['Female',])

,Gender,Branch,College_Tier,CGPA,Internships,Projects,Aptitude_Score,Communication_Score,Technical_Score,Backlogs,Attendance_Percentage,Certifications,Coding_Rating,Placement,Salary_LPA
0,NaN,IT,Tier 3,5.72,0,3,99,72,90,4,92.65,1,1806,0,0.00
1,NaN,ECE,Tier 3,8.10,5,3,86,69,81,3,89.56,2,1163,0,0.00
2,Male,ECE,Tier 1,6.08,5,5,99,85,92,1,71.25,2,1946,1,16.17
3,Male,CSE,Tier 1,7.22,2,2,61,64,41,3,73.49,6,1697,0,0.00
4,Male,IT,Tier 1,9.03,2,4,99,89,43,4,98.56,6,920,1,15.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Male,CIVIL,Tier 1,9.70,1,3,76,70,70,2,78.76,5,1367,1,17.49
4996,Male,EEE,Tier 1,7.33,0,4,79,84,57,3,63.34,0,1064,1,13.20
4997,NaN,EEE,Tier 1,6.61,5,7,63,58,80,3,60.31,0,1460,1,15.57
4998,Male,MECH,Tier 2,6.00,4,1,83,96,50,4,77.70,3,1070,0,0.00
4999,NaN,MECH,Tier 2,6.58,3,8,75,97,52,1,83.65,0,1974,1,13.58

16.loading a huge dataset in chunks

In [12]:
dfs = pd.read_csv('StudentPlacementData.csv',chunksize=5000)
for chunks in dfs:
    print(chunks.shape)

(5000, 15)